/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("WorkOrdersListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheWorkOrdersList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheWorkOrdersList.onFilterBar().iCheckFilterField("Equipment");
            Then.onTheWorkOrdersList.onFilterBar().iCheckFilterField("Status");
            Then.onTheWorkOrdersList.onFilterBar().iCheckFilterField("Priority");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheWorkOrdersList.onTable().iCheckColumns(undefined, {"WorkOrderNo":{"header":"Work Order"},"EquipmentName":{"header":"Equipment"},"ProcedureName":{"header":"Procedure"},"AssignedName":{"header":"Assigned To"},"Status":{"header":"Status"},"Priority":{"header":"Priority"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheWorkOrdersList.onFilterBar().iExecuteSearch();
            
            Then.onTheWorkOrdersList.onTable().iCheckRows();

            When.onTheWorkOrdersList.onTable().iPressRow(0);
            Then.onTheWorkOrdersObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});